project:
  type: website

website:
  title: "Kareem Amr"
  site-url: https://kareemamrr.github.io/
  favicon: profile.jpg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kareemamrr
      - icon: linkedin
        href: https://www.linkedin.com/in/kareemamrr/
format:
  html:
    theme:
      light: cosmo
      # dark: solar
    css: styles.css
    monofont: "Jetbrains Mono"
execute:
  freeze: auto

