project:
  type: website

website:
  title: "Kareem Amr"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kareemamrr
      - icon: twitter
        href: https://x.com/kxreem54
      - icon: linkedin
        href: https://www.linkedin.com/in/kareemamrr/
format:
  html:
    theme: cosmo
    css: styles.css
execute:
  freeze: auto

